name: Publish Docker Image

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Check out the repo
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub using credentials from GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # v2 is the current stable version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Step 3: Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4  # v4 is the current stable version
        with:
          images: bharu2003/myapp  # Replace with your Docker username and repository name
      
      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4  # v4 is the current stable version
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}  # Uses dynamically generated tags
          labels: ${{ steps.meta.outputs.labels }}  # Uses dynamically generated labels
